#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.

# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_LGSIC_SW49407)           += sw49407/
obj-$(CONFIG_LGE_TOUCH_LGSIC_SW49407_LUCYE)     += sw49407/
obj-$(CONFIG_LGE_TOUCH_LGSIC_SW49408)           += sw49408/

